server {
    listen 8443 ssl;
    listen [::]:8443 ssl;
    server_name test.talkchief.io;
    ssl_certificate /etc/nginx/kazoo-tls/fullchain.pem;
    ssl_certificate_key /etc/nginx/kazoo-tls/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    error_page 497 =301 https://test.talkchief.io:8443$request_uri;

    if ($host != test.talkchief.io) {
        return 301 https://test.talkchief.io:8443$request_uri;
    }

    location / {
        proxy_pass http://127.0.0.1:4520;
        proxy_http_version 1.1;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_read_timeout 360s;
        proxy_send_timeout 360s;
    }
}
