import {renderDocument} from './task-output.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const status={queued:'Queued',planning:'Planning',clarification:'Requirements need your input',running:'Teams in progress',verifying:'Verifying project scope',saving:'Saving verified delivery',done:'Scope verified',blocked:'Needs attention',cancelled:'Cancelled'};
export function projectWorkspace({api,open,content,feedback,showTask,isOpen}){
  let selected=null,dirty=false,items=[],last='';
  async function list(){selected=null;dirty=false;items=await api('/projects');open('projects','Program Manager');content.innerHTML=`<div class="space-settings-heading"><div><span class="space-eyebrow">PROJECT OFFICE</span><h3>From requirements to delivery</h3><p>Your Program Manager clarifies scope, coordinates team leads and verifies the complete project.</p></div><button id="spaceNewProject">+ New project</button></div><div class="space-project-list">${items.map(p=>`<button class="space-note" data-project="${p.id}"><b>${esc(p.title)}</b><span>${status[p.state]} · ${p.progress.approved}/${p.progress.total} team assignments approved</span><progress value="${p.progress.approved}" max="${p.progress.total||1}"></progress></button>`).join('')||'<div class="space-output-empty"><h3>One accountable owner for the whole project.</h3><p>Add the brief and source documents. The Program Manager checks for gaps before any team begins.</p></div>'}</div>`;content.querySelector('#spaceNewProject').onclick=create;content.querySelectorAll('[data-project]').forEach(b=>b.onclick=()=>detail(b.dataset.project));}
  function create(){selected=null;dirty=true;open('projects','New project');content.innerHTML=`<button class="secondary" id="projectBack">← Projects</button><form id="spaceProjectForm"><label>Project name<input name="title" required maxlength="160" placeholder="e.g. Product launch — October"></label><label>Requirements and definition of done<textarea name="brief" rows="6" required maxlength="20000" placeholder="What should this project deliver? Include scope, deadlines, constraints and expected artifacts."></textarea></label><label class="space-upload">Attach requirements or reference documents<input type="file" id="projectFiles" multiple accept=".pdf,.docx,.txt,.md,.csv"><small>PDF, DOCX, text, Markdown or CSV · Up to 10 files · 5 MB each · 150,000 extracted characters total</small></label><div id="projectDocuments"></div><div class="space-actions"><button type="submit">Send to Program Manager ↗</button></div><p>The Program Manager will ask about material gaps before distributing work. Teams use their configured tools and review rules.</p></form>`;let docs=[],uploading=false;content.querySelector('#projectBack').onclick=list;const files=content.querySelector('#projectFiles'),submit=content.querySelector('[type=submit]');
    const renderDocs=()=>{content.querySelector('#projectDocuments').innerHTML=docs.map((d,i)=>`<div class="space-document-file"><span>${esc(d.name)} <small>${d.content.length.toLocaleString()} characters ready</small></span><button type="button" class="secondary" data-remove-document="${i}">Remove</button></div>`).join('');content.querySelectorAll('[data-remove-document]').forEach(b=>b.onclick=()=>{docs.splice(+b.dataset.removeDocument,1);renderDocs();});};
    files.onchange=async()=>{uploading=true;submit.disabled=true;try{for(const file of files.files){if(docs.length>=10||file.size>5*1024*1024)throw new Error('Use up to 10 documents, no larger than 5 MB each.');feedback('Reading '+file.name+'…');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});const doc=await api('/projects/documents','POST',{name:file.name,data});if(docs.reduce((n,d)=>n+d.content.length,0)+doc.content.length>150000)throw new Error('Combined documents exceed 150,000 characters.');docs.push(doc);renderDocs();}feedback('Documents ready for the Program Manager.');}catch(e){feedback(e.message,true);}finally{uploading=false;submit.disabled=false;files.value='';}};
    content.querySelector('form').onsubmit=async e=>{e.preventDefault();if(uploading)return;submit.disabled=true;try{const fields=Object.fromEntries(new FormData(e.target));const p=await api('/projects','POST',{...fields,documents:docs});dirty=false;await detail(p.id);}catch(e){feedback(e.message,true);submit.disabled=false;}};
  }
  async function detail(id,poll=false){const p=await api('/projects/'+id);if(poll&&(!isOpen()||selected!==id||dirty))return;const signature=JSON.stringify(p);if(poll&&signature===last)return;last=signature;selected=id;dirty=false;if(!poll)open('projects',p.title);const y=content.scrollTop;const expanded=[...content.querySelectorAll('details[open]')].map(d=>d.querySelector('summary')?.textContent);content.innerHTML=`<button class="secondary" id="projectBack">← All projects</button><div class="space-phase-banner ${p.state==='verifying'?'reviewing':p.state}">${['planning','verifying'].includes(p.state)?'<i class="space-spinner"></i>':''}<div><b>${status[p.state]}</b><span>Program Manager · ${esc(p.model)} · ${esc(p.effort)} effort · ${p.calls}/10 coordination calls</span></div></div><p>${esc(p.summary||p.brief)}</p><div class="space-project-progress"><b>${p.progress.approved} / ${p.progress.total}</b><span>team assignments approved</span><progress value="${p.progress.approved}" max="${p.progress.total||1}"></progress></div>
    ${p.state==='clarification'?`<section class="space-project-questions"><h3>Resolve these requirements</h3><ol>${p.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ol><form id="projectAnswer"><label>Your clarifications<textarea name="text" rows="5" required></textarea></label><button type="submit">Update requirements & continue</button></form></section>`:''}
    ${p.error?`<aside class="space-task-blocker"><b>What needs attention</b><p>${esc(p.error)}</p><p>Open the affected team task to resolve its blocker, then resume project coordination.</p></aside>`:''}
    ${p.result?`<details ${p.state==='done'?'open':''}><summary>${p.state==='done'?'Project delivery':'Draft delivery — scope not approved'}</summary><div class="space-document">${renderDocument(p.result,'project').html}</div><button id="projectExport" class="secondary">Download delivery (.md)</button></details>`:''}
    <p class="space-footnote">${p.progress.calls ?? p.calls} total model calls · ${(p.progress.tokens ?? p.tokens).toLocaleString()} reported tokens across project coordination and current team assignments</p><h3>Scope & accountability</h3><div class="space-scope-list">${p.scope.map(r=>{const c=p.review?.coverage?.find(c=>c.id===r.id);return `<div><span>${c?.passed?'✓':'○'}</span><p><b>${esc(r.text)}</b><small>${esc(c?.evidence||'Assigned to: '+p.workstreams.filter(w=>w.requirements.includes(r.id)).map(w=>w.title).join(' · '))}</small></p></div>`;}).join('')||'<p>Scope mapping will appear after the requirements review.</p>'}</div><h3>Team workstreams</h3>${p.workstreams.map(w=>`<article class="space-project-stream"><span class="space-eyebrow">${esc(w.teamName || w.team)} · ${esc(w.state)}</span><h3>${esc(w.title)}</h3>${w.dependencies.length?`<p>Depends on ${w.dependencies.map(d=>esc(p.workstreams.find(w=>w.id===d)?.title||d)).join(', ')}</p>`:''}${w.subtasks.map(s=>`<p>${s.state==='done'?'✓':'○'} ${esc(s.title)} · ${esc(s.state)}${s.model?' · '+esc(s.model)+' / '+esc(s.effort):''}</p>`).join('')}${w.review?`<p>Lead feedback: ${esc(w.review)}</p>`:''}${w.taskId?`<button class="secondary" data-project-task="${w.taskId}">Open team plan & artifacts ↗</button>`:'<p>Waiting for prerequisites</p>'}</article>`).join('')}
    <details><summary>Requirements & source documents (${p.documents.length})</summary><p>${esc(p.brief)}</p>${p.documents.map(d=>`<details><summary>${esc(d.name)}</summary><pre>${esc(d.content)}</pre></details>`).join('')}</details><details><summary>Project activity</summary>${p.events.map(e=>`<p><small>${new Date(e.at).toLocaleString()}</small> · ${esc(e.message)}</p>`).join('')}</details><div class="space-actions">${p.state==='blocked'?'<button data-project-action="resume">Resume coordination</button>':''}${!['done','cancelled','saving'].includes(p.state)?'<button class="secondary" data-project-action="cancel">Cancel project</button>':''}</div>`;
    if(poll)content.querySelectorAll('details').forEach(d=>d.open=expanded.includes(d.querySelector('summary')?.textContent));
    content.scrollTop=poll?y:0;content.querySelector('#projectBack').onclick=list;content.querySelectorAll('[data-project-task]').forEach(b=>b.onclick=()=>showTask(b.dataset.projectTask));content.querySelectorAll('[data-project-action]').forEach(b=>b.onclick=async()=>{try{if(b.dataset.projectAction==='cancel'&&!confirm('Cancel this project and its unfinished team tasks?'))return;await api('/projects/'+id+'/'+b.dataset.projectAction,'POST',{});await detail(id);}catch(e){feedback(e.message,true);}});
    const form=content.querySelector('#projectAnswer');if(form){form.oninput=()=>dirty=true;form.onsubmit=async e=>{e.preventDefault();try{await api('/projects/'+id+'/answer','POST',{text:form.elements.text.value});dirty=false;await detail(id);}catch(e){feedback(e.message,true);}};}
    if(content.querySelector('#projectExport'))content.querySelector('#projectExport').onclick=()=>{const url=URL.createObjectURL(new Blob([p.result],{type:'text/markdown'}));const a=document.createElement('a');a.href=url;a.download=p.title.replace(/[^a-z0-9-]/gi,'-')+'.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  }
  return {open:list,refresh:async()=>{items=await api('/projects');if(selected&&isOpen()&&!dirty)await detail(selected,true);},activity:()=>items.find(p=>['planning','verifying'].includes(p.state))||items.find(p=>p.state==='running'),items:()=>items};
}
